name: Build and publish .gba file
on:
  push:
    branches: [ main ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: developerforhire/gba-dkp-base:0.0.1
      volumes:
        - .:/volume_mount
      options: --cpus 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Add DevKitArm to PATH
        run: |
          echo "DEVKITARM=${DEVKITPRO}/devkitARM" >> $GITHUB_ENV
          echo "PATH=${DEVKITARM}/bin:${PATH}" >> $GITHUB_ENV
      
      - name: Build .gba file
        run: |
          make assets
          make
      
      - name: Publish .gba file to the realeases, using the commit history as the description
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/*.gba
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ github.event.head_commit.message }}
          tag: ${{ github.sha }}
          draft: false
          prerelease: true
